SMISrival/Controllers/CreateGradesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SMISrival.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SMISrival.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CreateGradesController : Controller
    {
        private readonly ApplicationDbContext _db;
        [BindProperty]
        public CreateGrade CreateGrade { get; set; }
        public CreateGradesController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Upsert(int? id)
        {
            CreateGrade = new CreateGrade();
            if (id == null)
            {
                //create
                return View(CreateGrade);
            }
            //update
            CreateGrade = _db.CreateGrades.FirstOrDefault(u => u.Id == id);
            if (CreateGrade == null)
            {
                return NotFound();
            }
            return View(CreateGrade);
        }

        public IActionResult Detail(int? id)
        {
            CreateGrade = new CreateGrade();
            if (id == null)
            {
                //create
                return View(CreateGrade);
            }
            //update
            CreateGrade = _db.CreateGrades.FirstOrDefault(u => u.Id == id);
            if (CreateGrade == null)
            {
                return NotFound();
            }
            return View(CreateGrade);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert()
        {
            if (ModelState.IsValid)
            {
                if (CreateGrade.Id == 0)
                {
                    //create
                    _db.CreateGrades.Add(CreateGrade);
                }
                else
                {
                    _db.CreateGrades.Update(CreateGrade);
                }
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(CreateGrade);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Detail()
        {
            if (ModelState.IsValid)
            {
                if (CreateGrade.Id == 0)
                {
                    //create
                    _db.CreateGrades.Add(CreateGrade);
                }
                else
                {
                    _db.CreateGrades.Update(CreateGrade);
                }
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(CreateGrade);
        }



        #region API Calls
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            return Json(new { data = await _db.CreateGrades.ToListAsync() });
        }


        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var creategradesFromDb = await _db.CreateGrades.FirstOrDefaultAsync(u => u.Id == id);
            if (creategradesFromDb == null)
            {
                return Json(new { success = false, message = "Error while Deleting" });
            }
            _db.CreateGrades.Remove(creategradesFromDb);
            await _db.SaveChangesAsync();
            return Json(new { success = true, message = "Delete successful" });
        }
        #endregion

    }
}

SMISrival/Controllers/GradessController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SMISrival.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SMISrival.Controllers
{
    [Authorize]
    public class GradessController : Controller
    {
        private readonly ApplicationDbContext _db;
        [BindProperty]
        public Grades Grades { get; set; }
        public GradessController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View();
        }

        

        public IActionResult Detail(int? id)
        {
            Grades = new Grades();
            if (id == null)
            {
                //create
                return View(Grades);
            }
            //update
            Grades = _db.Grades.FirstOrDefault(u => u.Id == id);
            if (Grades == null)
            {
                return NotFound();
            }
            return View(Grades);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Detail()
        {
            if (ModelState.IsValid)
            {
                if (Grades.Id == 0)
                {
                    //create
                    _db.Grades.Add(Grades);
                }
                else
                {
                    _db.Grades.Update(Grades);
                }
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(Grades);
        }



        #region API Calls
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            return Json(new { data = await _db.CreateGrades.ToListAsync() });
        }
        #endregion

    }
}

SMISrival/Controllers/StudentsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SMISrival.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SMISrival.Controllers
{
    [Authorize]
    public class StudentsController : Controller
    {
        
        private readonly ApplicationDbContext _db;
        [BindProperty]
        public Student Studnet { get; set; }
        public StudentsController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Upsert(int? id)
        {
            Studnet = new Student();
            if (id == null)
            {
                //create
                return View(Studnet);
            }
            //update
            Studnet = _db.Students.FirstOrDefault(u => u.Id == id);
            if (Studnet == null)
            {
                return NotFound();
            }
            return View(Studnet);
        }

        public IActionResult Detail(int? id)
        {
            Studnet = new Student();
            if (id == null)
            {
                //create
                return View(Studnet);
            }
            //update
            Studnet = _db.Students.FirstOrDefault(u => u.Id == id);
            if (Studnet == null)
            {
                return NotFound();
            }
            return View(Studnet);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert()
        {
            if (ModelState.IsValid)
            {
                if (Studnet.Id == 0)
                {
                    //create
                    _db.Students.Add(Studnet);
                }
                else
                {
                    _db.Students.Update(Studnet);
                }
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(Studnet);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Detail()
        {
            if (ModelState.IsValid)
            {
                if (Studnet.Id == 0)
                {
                    //create
                    _db.Students.Add(Studnet);
                }
                else
                {
                    _db.Students.Update(Studnet);
                }
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(Studnet);
        }



        #region API Calls
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            return Json(new { data = await _db.Students.ToListAsync() });
        }

        [Authorize(Roles = "Admin")]
        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var studentFromDb = await _db.Students.FirstOrDefaultAsync(u => u.Id == id);
            if (studentFromDb == null)
            {
                return Json(new { success = false, message = "Error while Deleting" });
            }
            _db.Students.Remove(studentFromDb);
            await _db.SaveChangesAsync();
            return Json(new { success = true, message = "Delete successful" });
        }
        #endregion
    }
}

SMISrival/Controllers/TeachersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SMISrival.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SMISrival.Controllers
{
    [Authorize(Roles = "Admin")]
    public class TeachersController : Controller
    {
        private readonly ApplicationDbContext _db;
        [BindProperty]
        public Teacher Teacher { get; set; }
        public TeachersController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Upsert(int? id)
        {
            Teacher = new Teacher();
            if (id == null)
            {
                //create
                return View(Teacher);
            }
            //update
            Teacher = _db.Teachers.FirstOrDefault(u => u.Id == id);
            if (Teacher == null)
            {
                return NotFound();
            }
            return View(Teacher);
        }

        public IActionResult Detail(int? id)
        {
            Teacher = new Teacher();
            if (id == null)
            {
                //create
                return View(Teacher);
            }
            //update
            Teacher = _db.Teachers.FirstOrDefault(u => u.Id == id);
            if (Teacher == null)
            {
                return NotFound();
            }
            return View(Teacher);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert()
        {
            if (ModelState.IsValid)
            {
                if (Teacher.Id == 0)
                {
                    //create
                    _db.Teachers.Add(Teacher);
                }
                else
                {
                    _db.Teachers.Update(Teacher);
                }
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(Teacher);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Detail()
        {
            if (ModelState.IsValid)
            {
                if (Teacher.Id == 0)
                {
                    //create
                    _db.Teachers.Add(Teacher);
                }
                else
                {
                    _db.Teachers.Update(Teacher);
                }
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(Teacher);
        }



        #region API Calls
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            return Json(new { data = await _db.Teachers.ToListAsync() });
        }


        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var studentFromDb = await _db.Teachers.FirstOrDefaultAsync(u => u.Id == id);
            if (studentFromDb == null)
            {
                return Json(new { success = false, message = "Error while Deleting" });
            }
            _db.Teachers.Remove(studentFromDb);
            await _db.SaveChangesAsync();
            return Json(new { success = true, message = "Delete successful" });
        }
        #endregion
    }
}

SMISrival/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SMISrival</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Students" asp-action="Index">SMISrival</a>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial.cshtml" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="Index">Student List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teachers" asp-action="Index">Teachers List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Gradess" asp-action="Index">Grades List</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark"  asp-controller="CreateGrades" asp-action="Index">Create Grades</a>
                                </li>
                            }
                        }
                    </ul>
                </div>
            </div>        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - SMISrival
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    @RenderSection("Scripts", required: false)
    @await RenderSectionAsync("Styles", required: false)
</body>
</html>