SMISrival/Areas/Admin/Controllers/AdminHomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SMISrival.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class AdminHomeController : Controller
    {


        private readonly RoleManager<IdentityRole> rolemanager;
        public AdminHomeController(RoleManager<IdentityRole> _roleManager)
        {
            rolemanager = _roleManager;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult CreateRole()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateRole(string roleName)
        {

            if (!await rolemanager.RoleExistsAsync(roleName))
            {

                await rolemanager.CreateAsync(new IdentityRole(roleName));
            }

            return View();
        }
    }
}

SMISrival/Areas/Admin/Views/AdminHome/CreateRole.cshtml
<h1>Create new roles</h1>


<div class="container row p-0 m-0">
    <div class="col-6">
        <form asp-controller="AdminHome" asp-action="CreateRole" method="post">
            <input type="text" name="roleName" value="" />
            <input type="submit" name="submit" value="Add" />
        </form>
    </div>
</div>

SMISrival/Areas/Admin/Views/AdminHome/Index.cshtml
<br/>

<div class="container row p-0 m-0">
    <div class="col-6">
        <h1 class="text-info">Welcome Home Admin</h1>
    </div>
</div>